#[cfg(feature = "extended-surfaces")]
pub mod adversarial_resilience_metrics;
#[cfg(feature = "extended-surfaces")]
pub mod benchmark_methodology;
pub mod benchmark_suite;
#[cfg(feature = "extended-surfaces")]
pub mod compatibility_correctness_metrics;
#[cfg(feature = "extended-surfaces")]
pub mod containment_revocation_metrics;
pub mod counterfactual_replay;
#[cfg(feature = "extended-surfaces")]
pub mod enterprise_governance;
pub mod evidence_replay_validator;
#[cfg(feature = "extended-surfaces")]
pub mod external_replication_claims;
#[cfg(feature = "extended-surfaces")]
pub mod frontier_demo_gate;
#[cfg(feature = "extended-surfaces")]
pub mod migration_incident_datasets;
#[cfg(feature = "extended-surfaces")]
pub mod migration_speed_failure_metrics;
#[cfg(feature = "extended-surfaces")]
pub mod migration_validation_cohorts;
#[cfg(feature = "extended-surfaces")]
pub mod partner_lighthouse_programs;
#[cfg(feature = "extended-surfaces")]
pub mod performance_hardening_metrics;
#[cfg(feature = "extended-surfaces")]
pub mod profile_tuning_harness;
#[cfg(feature = "extended-surfaces")]
pub mod redteam_evaluations;
pub mod replay_bundle;
#[cfg(feature = "extended-surfaces")]
pub mod replay_determinism_metrics;
#[cfg(feature = "extended-surfaces")]
pub mod report_output_contract;
#[cfg(feature = "extended-surfaces")]
pub mod repro_bundle_export;
#[cfg(feature = "extended-surfaces")]
pub mod reputation_graph_apis;
#[cfg(feature = "extended-surfaces")]
pub mod safe_extension_onboarding;
#[cfg(feature = "extended-surfaces")]
pub mod security_ops_case_studies;
#[cfg(feature = "extended-surfaces")]
pub mod security_trust_metrics;
#[cfg(feature = "extended-surfaces")]
pub mod transparent_reports;
#[cfg(feature = "extended-surfaces")]
pub mod trust_economics_dashboard;
#[cfg(feature = "extended-surfaces")]
pub mod vef_perf_budget_gate;
#[cfg(feature = "extended-surfaces")]
pub mod verifier_benchmark_releases;
#[cfg(feature = "extended-surfaces")]
pub mod verifier_toolkit;
#[cfg(feature = "extended-surfaces")]
pub mod version_benchmark_standards;

#[cfg(test)]
mod benchmark_suite_conformance_tests;
#[cfg(test)]
mod replay_bundle_conformance_tests;
